# Generated by Django 3.2.13 on 2022-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviesdata',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'moviesdata',
            },
        ),
    ]
